title: Edoardo Basili
description: Fisioterapista con Master in Tecniche Manuali integrate ed Osteopatiche nei disturbi neuro-muscolo-scheletrici.

url: "https://edoardobasili.github.io"
baseurl: ""

lang: it

logo: "/assets/img/logo-eb.svg"

whatsapp_number: "393513473025"
whatsapp_message: "Ciao Edoardo, vorrei informazioni per prenotare una visita."

email: "edoardo.basili@outlook.it"

plugins:
  - jekyll-seo-tag

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock